In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter(action='ignore')

In [94]:
df1=pd.read_csv('/content/DOW30.csv')
df2=pd.read_csv('/content/NASDAQ.csv')
df3=pd.read_csv('/content/SP500.csv')

# 전처리

In [121]:
x_data=df1.iloc[:,2:]
y_data=df1[['LABEL']]
x_data2=df2.iloc[:,2:]
y_data2=df2[['LABEL']]
x_data3=df3.iloc[:,2:]
y_data3=df3[['LABEL']]

# 표준화

In [123]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled = scaler.fit_transform(x_data)
scaler2 = StandardScaler()
scaled2 = scaler2.fit_transform(x_data2)
scaler3 = StandardScaler()
scaled3 = scaler3.fit_transform(x_data3)

# 테스트 트레인 스플릿

In [124]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(scaled,y_data,test_size=0.2,random_state=121)
X_train2,X_test2,y_train2,y_test2=train_test_split(scaled2,y_data2,test_size=0.2,random_state=121)
X_train3,X_test3,y_train3,y_test3=train_test_split(scaled3,y_data3,test_size=0.2,random_state=121)

# 검증 함수

In [100]:
from sklearn.metrics import confusion_matrix,precision_score, recall_score,f1_score, roc_auc_score

def get_clf_eval(y_test, pred=None, pred_proba=None):
    confusion = confusion_matrix( y_test, pred)
    accuracy = accuracy_score(y_test , pred)
    precision = precision_score(y_test , pred)
    recall = recall_score(y_test , pred)
    f1 = f1_score(y_test,pred)
    # ROC-AUC 추가 
    roc_auc = roc_auc_score(y_test, pred_proba)
    print('오차 행렬')
    print(confusion)
    # ROC-AUC print 추가
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f},\
    F1: {3:.4f}, AUC:{4:.4f}'.format(accuracy, precision, recall, f1, roc_auc))

In [101]:
grid_cv.get_params()

{'cv': 2,
 'error_score': nan,
 'estimator': RandomForestClassifier(random_state=0),
 'estimator__bootstrap': True,
 'estimator__ccp_alpha': 0.0,
 'estimator__class_weight': None,
 'estimator__criterion': 'gini',
 'estimator__max_depth': None,
 'estimator__max_features': 'auto',
 'estimator__max_leaf_nodes': None,
 'estimator__max_samples': None,
 'estimator__min_impurity_decrease': 0.0,
 'estimator__min_samples_leaf': 1,
 'estimator__min_samples_split': 2,
 'estimator__min_weight_fraction_leaf': 0.0,
 'estimator__n_estimators': 100,
 'estimator__n_jobs': None,
 'estimator__oob_score': False,
 'estimator__random_state': 0,
 'estimator__verbose': 0,
 'estimator__warm_start': False,
 'n_jobs': -1,
 'param_grid': {'max_depth': [6],
  'min_samples_leaf': [6, 7, 8],
  'min_samples_split': [6, 7, 8],
  'n_estimators': [90]},
 'pre_dispatch': '2*n_jobs',
 'refit': True,
 'return_train_score': False,
 'scoring': None,
 'verbose': 0}

# 결정트리 및 개별모델

## 의사결정나무

In [126]:
from sklearn.tree import DecisionTreeClassifier
dt_clf = DecisionTreeClassifier(random_state=156)
dt_clf.fit(X_train , y_train)
dt_pred=dt_clf.predict(X_test)

dt_clf2 = DecisionTreeClassifier(random_state=156)
dt_clf2.fit(X_train2 , y_train2)
dt_pred2=dt_clf2.predict(X_test2)

dt_clf3 = DecisionTreeClassifier(random_state=156)
dt_clf3.fit(X_train3 , y_train3)
dt_pred3=dt_clf3.predict(X_test3)

a=accuracy_score(y_test,dt_pred)
b=accuracy_score(y_test2,dt_pred2)
c=accuracy_score(y_test3,dt_pred3)
print('DOW :',a,'NASDAQ : ',b,'SP500 : ',c)

DOW : 0.5142857142857142 NASDAQ :  0.5020408163265306 SP500 :  0.49183673469387756


## 로지스틱 회귀

In [127]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state=156)
lr.fit(X_train , y_train)
lr_pred=lr.predict(X_test)

lr2 = LogisticRegression(random_state=156)
lr2.fit(X_train2 , y_train2)
lr_pred2=lr2.predict(X_test2)

lr3 = LogisticRegression(random_state=156)
lr3.fit(X_train3 , y_train3)
lr_pred3=lr3.predict(X_test3)

## knn근접
떤 데이터가 주어지면 그 주변(이웃)의 데이터를 살펴본 뒤 더 많은 데이터가 포함되어 있는 범주로 분류하는 방식
K: 참고할 이웃의 수. 기본값은 5

In [128]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=8)

classifiers = [lr, knn_clf]
for classifier in classifiers:
    classifier.fit(X_train , y_train)
    pred = classifier.predict(X_test)
    class_name= classifier.__class__.__name__
    print('dow {0} 정확도: {1:.4f}'.format(class_name, accuracy_score(y_test , pred)))

knn_clf2 = KNeighborsClassifier(n_neighbors=8)

classifiers2 = [lr2, knn_clf2]
for classifier in classifiers2:
    classifier.fit(X_train2 , y_train2)
    pred2 = classifier.predict(X_test2)
    class_name2= classifier.__class__.__name__
    print('nasdaq {0} 정확도: {1:.4f}'.format(class_name2, accuracy_score(y_test2 , pred2)))

knn_clf3 = KNeighborsClassifier(n_neighbors=8)

classifiers3 = [lr3, knn_clf3]
for classifier in classifiers3:
    classifier.fit(X_train3 , y_train3)
    pred3 = classifier.predict(X_test3)
    class_name3= classifier.__class__.__name__
    print('sp500 {0} 정확도: {1:.4f}'.format(class_name3, accuracy_score(y_test3 , pred3)))


dow LogisticRegression 정확도: 0.5469
dow KNeighborsClassifier 정확도: 0.5327
nasdaq LogisticRegression 정확도: 0.5592
nasdaq KNeighborsClassifier 정확도: 0.4918
sp500 LogisticRegression 정확도: 0.5449
sp500 KNeighborsClassifier 정확도: 0.4571


#앙상블

## VotingClassifier

In [129]:
from sklearn.ensemble import VotingClassifier
vo_clf = VotingClassifier( estimators=[('LR',lr),('KNN',knn_clf)] , voting='soft' )

vo_clf.fit(X_train , y_train)
pred = vo_clf.predict(X_test)
print('dow Voting 분류기 정확도: {0:.4f}'.format(accuracy_score(y_test , pred)))

vo_clf2 = VotingClassifier( estimators=[('LR',lr2),('KNN',knn_clf2)] , voting='soft' )

vo_clf2.fit(X_train2 , y_train2)
pred2 = vo_clf2.predict(X_test2)
print('nasdaq Voting 분류기 정확도: {0:.4f}'.format(accuracy_score(y_test2 , pred2)))

vo_clf3 = VotingClassifier( estimators=[('LR',lr3),('KNN',knn_clf3)] , voting='soft' )

vo_clf3.fit(X_train3 , y_train3)
pred3 = vo_clf3.predict(X_test3)
print('sp500 Voting 분류기 정확도: {0:.4f}'.format(accuracy_score(y_test3 , pred3)))

dow Voting 분류기 정확도: 0.5163
nasdaq Voting 분류기 정확도: 0.5102
sp500 Voting 분류기 정확도: 0.5204


## SVM(보팅)
  - 보팅: 서로 다른 알고리즘 여러개 결합. 선형회귀, K 최근접 이웃, SVM 알고리즘 등 다양한 알고리즘을 결합하여 만든다.
    - 하드 보팅: 다수 분류기가 결정한 예측을 선택
    - 소프트 보팅: 분류기들의 레이블 결정 확률의 평균을 내어 이 중 가장 큰 확률의 레이블 선택
    - svm
      - 결정 경계(Decision Boundary), 즉 분류를 위한 기준 선을 정의하는 모델
최적의 경계를 찾는 것이 목적
      - 분류하는 데이터들 사이의 마진이 최대가 되는 선이 좋다    

In [130]:
from sklearn import svm
clf = svm.SVC()

clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)

acc = accuracy_score(y_test, y_pred)

print('dow svm 정확도:', acc)

clf2 = svm.SVC()

clf2.fit(X_train2,y_train2)
y_pred2=clf2.predict(X_test2)

acc2 = accuracy_score(y_test2, y_pred2)

print('nasdaq svm 정확도:', acc2)


clf3 = svm.SVC()

clf3.fit(X_train3,y_train3)
y_pred3=clf.predict(X_test3)

acc3 = accuracy_score(y_test3, y_pred3)

print('sp500 svm 정확도:', acc3)

dow svm 정확도: 0.5530612244897959
nasdaq svm 정확도: 0.5653061224489796
sp500 svm 정확도: 0.5387755102040817


## RandomForestClassifier(배깅)
  - 배깅: 같은 알고리즘 여러개 결합. 랜덤 포레스트 알고리즘이 이에 속함
      - 랜덤 포레스트: 대표적 배깅 알고리즘으로 빠르고 예측 성능이 좋다 결정트리 여러개로 구성.
      - 각 분류기는 서로 다른 데이터셋을 학습하지만 일부 데이터는 중첩되어 있다. 이를 부트스트래핑이라 함.

In [131]:
# randomforestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf_clf=RandomForestClassifier(random_state=0)
rf_clf.fit(X_train,y_train)
pred=rf_clf.predict(X_test)
a=accuracy_score(y_test,pred)

rf_clf2=RandomForestClassifier(random_state=0)
rf_clf2.fit(X_train2,y_train2)
pred2=rf_clf2.predict(X_test2)
b=accuracy_score(y_test2,pred2)

rf_clf3=RandomForestClassifier(random_state=0)
rf_clf3.fit(X_train3,y_train3)
pred3=rf_clf3.predict(X_test3)
c=accuracy_score(y_test3,pred3)

print('DOW :',a,'NASDAQ : ',b,'SP500 : ',c)

DOW : 0.5102040816326531 NASDAQ :  0.5387755102040817 SP500 :  0.5244897959183673


## GridSearchCV(최적파라미터찾기)

In [132]:

from sklearn.model_selection import GridSearchCV

params = {
    'n_estimators':[90],
    'max_depth' : [6], 
    'min_samples_leaf' : [6,7,8],
    'min_samples_split' : [6,7,8]
}
# RandomForestClassifier 객체 생성 후 GridSearchCV 수행
grid_cv = GridSearchCV(rf_clf , param_grid=params , cv=2, n_jobs=-1 )
grid_cv.fit(X_train , y_train)

grid_cv2 = GridSearchCV(rf_clf2 , param_grid=params , cv=2, n_jobs=-1 )
grid_cv2.fit(X_train2 , y_train2)

grid_cv3 = GridSearchCV(rf_clf3 , param_grid=params , cv=2, n_jobs=-1 )
grid_cv3.fit(X_train3 , y_train3)

print('dow 최적 하이퍼 파라미터:\n', grid_cv.best_params_)
print('dow 최고 예측 정확도: {0:.4f}'.format(grid_cv.best_score_))

print('nasdaq 최적 하이퍼 파라미터:\n', grid_cv2.best_params_)
print('nasdaq 최고 예측 정확도: {0:.4f}'.format(grid_cv2.best_score_))

print('sp500  최적 하이퍼 파라미터:\n', grid_cv3.best_params_)
print('sp500 최고 예측 정확도: {0:.4f}'.format(grid_cv3.best_score_))

dow 최적 하이퍼 파라미터:
 {'max_depth': 6, 'min_samples_leaf': 8, 'min_samples_split': 6, 'n_estimators': 90}
dow 최고 예측 정확도: 0.5373
nasdaq 최적 하이퍼 파라미터:
 {'max_depth': 6, 'min_samples_leaf': 7, 'min_samples_split': 6, 'n_estimators': 90}
nasdaq 최고 예측 정확도: 0.5465
sp500  최적 하이퍼 파라미터:
 {'max_depth': 6, 'min_samples_leaf': 8, 'min_samples_split': 6, 'n_estimators': 90}
sp500 최고 예측 정확도: 0.5516


In [134]:
gb_pred = grid_cv.best_estimator_.predict(X_test)
gb_accuracy = accuracy_score(y_test, gb_pred)

gb_pred2 = grid_cv2.best_estimator_.predict(X_test2)
gb_accuracy2 = accuracy_score(y_test2, gb_pred2)

gb_pred3 = grid_cv3.best_estimator_.predict(X_test3)
gb_accuracy3 = accuracy_score(y_test3, gb_pred3)

print('dow GridSearchCV 정확도: {0:.4f}'.format(gb_accuracy))
print('nasdaq GridSearchCV 정확도: {0:.4f}'.format(gb_accuracy2))
print('sp500 GridSearchCV 정확도: {0:.4f}'.format(gb_accuracy3))

dow GridSearchCV 정확도: 0.5571
nasdaq GridSearchCV 정확도: 0.5510
sp500 GridSearchCV 정확도: 0.5286


## GBClassifier(부스팅)
    - 여러 약한 학습기가 순차적으로 느슨하게 분류하고 오분류된 데이터에 대해 가중치를 부여하여, 예측 결정 기준을 모두 결합해 예측을 수행
    - 가중치 업데이트를 경사 하강법을 이용

In [135]:

from sklearn.ensemble import GradientBoostingClassifier
import time

# GBM 수행 시간 측정을 위함. 시작 시간 설정.
start_time = time.time()

gb_clf = GradientBoostingClassifier(random_state=0)
gb_clf.fit(X_train , y_train)
gb_pred = gb_clf.predict(X_test)

gb_accuracy = accuracy_score(y_test, gb_pred)

gb_clf2 = GradientBoostingClassifier(random_state=0)
gb_clf2.fit(X_train2 , y_train2)
gb_pred2 = gb_clf2.predict(X_test2)

gb_accuracy2 = accuracy_score(y_test2, gb_pred2)

gb_clf3 = GradientBoostingClassifier(random_state=0)
gb_clf3.fit(X_train3 , y_train3)
gb_pred3 = gb_clf3.predict(X_test3)

gb_accuracy3 = accuracy_score(y_test3, gb_pred3)

print('dow GBClassifier 정확도: {0:.4f}'.format(gb_accuracy))

print('nasdaq GBClassifier 정확도: {0:.4f}'.format(gb_accuracy2))

print('sp500 GBClassifier 정확도: {0:.4f}'.format(gb_accuracy3))


dow GBClassifier 정확도: 0.5367
nasdaq GBClassifier 정확도: 0.5449
sp500 GBClassifier 정확도: 0.5429


## xgboost

    - GBM에 기반하고 있고, 단점인 느린 수행 시간 및 과적합 등의 문제를 해결했으며 특히 병렬 학습이 가능해 기존 GBM보다 빠른 학습이 가능하다.
    - 뛰어난 예측 성능
    - GBM 대비 빠른 수행 시간
    - 과적합 규제
    - 나무 가지치기: 의미 없는 분할 제거
    - 결손값 자체 처리
    - 자체 내장된 교차 검증

In [140]:
import xgboost as xgb
from xgboost import plot_importance

dtrain = xgb.DMatrix(data=X_train , label=y_train)
dtest = xgb.DMatrix(data=X_test , label=y_test)

dtrain2 = xgb.DMatrix(data=X_train2 , label=y_train2)
dtest2 = xgb.DMatrix(data=X_test2 , label=y_test2)

dtrain3 = xgb.DMatrix(data=X_train3 , label=y_train3)
dtest3 = xgb.DMatrix(data=X_test3 , label=y_test3)

params = { 'max_depth':3,
           'eta': 0.1,
           'objective':'binary:logistic',
           'eval_metric':'logloss'
        }
num_rounds = 400

wlist = [(dtrain,'train'),(dtest,'eval') ]
wlist2 = [(dtrain2,'train'),(dtest2,'eval') ]
wlist3 = [(dtrain3,'train'),(dtest3,'eval') ]

xgb_model = xgb.train(params = params , dtrain=dtrain , num_boost_round=num_rounds ,early_stopping_rounds=100, evals=wlist )
pred_probs = xgb_model.predict(dtest)

xgb_model2 = xgb.train(params = params , dtrain=dtrain2 , num_boost_round=num_rounds ,early_stopping_rounds=100, evals=wlist2 )
pred_probs2 = xgb_model2.predict(dtest2)

xgb_model3 = xgb.train(params = params , dtrain=dtrain3 , num_boost_round=num_rounds ,early_stopping_rounds=100, evals=wlist3 )
pred_probs3 = xgb_model3.predict(dtest3)
# print('predict( ) 수행 결과값을 10개만 표시, 예측 확률 값으로 표시됨')
# print(np.round(pred_probs[:10],3))

[0]	train-logloss:0.689476	eval-logloss:0.692232
Multiple eval metrics have been passed: 'eval-logloss' will be used for early stopping.

Will train until eval-logloss hasn't improved in 100 rounds.
[1]	train-logloss:0.686355	eval-logloss:0.691671
[2]	train-logloss:0.684083	eval-logloss:0.691199
[3]	train-logloss:0.682158	eval-logloss:0.690398
[4]	train-logloss:0.680076	eval-logloss:0.689637
[5]	train-logloss:0.678678	eval-logloss:0.688865
[6]	train-logloss:0.676363	eval-logloss:0.687905
[7]	train-logloss:0.673981	eval-logloss:0.687713
[8]	train-logloss:0.672732	eval-logloss:0.687203
[9]	train-logloss:0.670605	eval-logloss:0.686835
[10]	train-logloss:0.669011	eval-logloss:0.687292
[11]	train-logloss:0.667996	eval-logloss:0.687337
[12]	train-logloss:0.666755	eval-logloss:0.686592
[13]	train-logloss:0.665935	eval-logloss:0.686754
[14]	train-logloss:0.664979	eval-logloss:0.686693
[15]	train-logloss:0.664456	eval-logloss:0.68624
[16]	train-logloss:0.663099	eval-logloss:0.686167
[17]	train-

In [141]:
# 예측 확률이 0.5 보다 크면 1 , 그렇지 않으면 0 으로 예측값 결정하여 List 객체인 preds에 저장 
xgb_preds = [ 1 if x > 0.5 else 0 for x in pred_probs ]
print('dow 예측값 10개만 표시:',xgb_preds[:10])

xgb_preds2 = [ 1 if x > 0.5 else 0 for x in pred_probs2 ]
print('nasdaq 예측값 10개만 표시:',xgb_preds2[:10])

xgb_preds3 = [ 1 if x > 0.5 else 0 for x in pred_probs3 ]
print('sp500 예측값 10개만 표시:',xgb_preds3[:10])

dow 예측값 10개만 표시: [1, 0, 0, 1, 1, 0, 1, 1, 1, 1]
nasdaq 예측값 10개만 표시: [1, 1, 0, 1, 1, 1, 1, 1, 1, 0]
sp500 예측값 10개만 표시: [1, 1, 0, 1, 1, 1, 1, 1, 1, 0]


In [142]:
print('dow')
get_clf_eval(y_test , xgb_preds, pred_probs)
print('nasdaq')
get_clf_eval(y_test2 , xgb_preds2, pred_probs2)
print('sp500')
get_clf_eval(y_test3 , xgb_preds3, pred_probs3)

dow
오차 행렬
[[ 70 136]
 [ 98 186]]
정확도: 0.5224, 정밀도: 0.5776, 재현율: 0.6549,    F1: 0.6139, AUC:0.5292
nasdaq
오차 행렬
[[ 55 162]
 [ 67 206]]
정확도: 0.5327, 정밀도: 0.5598, 재현율: 0.7546,    F1: 0.6427, AUC:0.5157
sp500
오차 행렬
[[ 57 155]
 [ 73 205]]
정확도: 0.5347, 정밀도: 0.5694, 재현율: 0.7374,    F1: 0.6426, AUC:0.4885


## LightGBM
    - XGBoost보다 학습 시간이 훨씬 적고 메모리 사용량도 작다. 하지만 적은 데이터 세트에 적용할 경우 과적합이 쉽게 발생하는 단점이 있다.
    - 앞서 살펴본 알고리즘들은 균형 트리를 생성하느라 시간 및 비용이 많이 드는 단점을 극복하기 위해 리프 중심 트리 분할 방법을 사용한다. 이 방법은 균형을 맞추지 않고 계속 분할을 진행하여 트리 깊이가 깊어지고 비대칭 트리가 생성된다.
    - 더 빠른 학습과 예측 수행 시간
    - 더 작은 메모리 사용량
    - 카테고리형 피처의 자동 변환과 최적 분할

In [143]:
from lightgbm import LGBMClassifier


lgbm_wrapper = LGBMClassifier(n_estimators=400)


evals = [(X_test, y_test)]
lgbm_wrapper.fit(X_train, y_train, early_stopping_rounds=100, eval_metric="logloss", 
                 eval_set=evals, verbose=True)
lgbm_preds = lgbm_wrapper.predict(X_test)
pred_proba = lgbm_wrapper.predict_proba(X_test)[:, 1]
a=accuracy_score(y_test,lgbm_preds)

lgbm_wrapper2 = LGBMClassifier(n_estimators=400)


evals2 = [(X_test2, y_test2)]
lgbm_wrapper2.fit(X_train2, y_train2, early_stopping_rounds=100, eval_metric="logloss", 
                 eval_set=evals2, verbose=True)
lgbm_preds2 = lgbm_wrapper2.predict(X_test2)
pred_proba2 = lgbm_wrapper2.predict_proba(X_test2)[:, 1]
b=accuracy_score(y_test2,lgbm_preds2)

lgbm_wrapper3 = LGBMClassifier(n_estimators=400)


evals3 = [(X_test3, y_test3)]
lgbm_wrapper3.fit(X_train3, y_train3, early_stopping_rounds=100, eval_metric="logloss", 
                 eval_set=evals3, verbose=True)
lgbm_preds3 = lgbm_wrapper3.predict(X_test3)
pred_proba3 = lgbm_wrapper3.predict_proba(X_test3)[:, 1]
c=accuracy_score(y_test3,lgbm_preds3)

[1]	valid_0's binary_logloss: 0.684069	valid_0's binary_logloss: 0.684069
Training until validation scores don't improve for 100 rounds.
[2]	valid_0's binary_logloss: 0.684131	valid_0's binary_logloss: 0.684131
[3]	valid_0's binary_logloss: 0.685293	valid_0's binary_logloss: 0.685293
[4]	valid_0's binary_logloss: 0.686812	valid_0's binary_logloss: 0.686812
[5]	valid_0's binary_logloss: 0.687946	valid_0's binary_logloss: 0.687946
[6]	valid_0's binary_logloss: 0.68915	valid_0's binary_logloss: 0.68915
[7]	valid_0's binary_logloss: 0.691454	valid_0's binary_logloss: 0.691454
[8]	valid_0's binary_logloss: 0.692257	valid_0's binary_logloss: 0.692257
[9]	valid_0's binary_logloss: 0.694349	valid_0's binary_logloss: 0.694349
[10]	valid_0's binary_logloss: 0.69735	valid_0's binary_logloss: 0.69735
[11]	valid_0's binary_logloss: 0.698437	valid_0's binary_logloss: 0.698437
[12]	valid_0's binary_logloss: 0.699153	valid_0's binary_logloss: 0.699153
[13]	valid_0's binary_logloss: 0.700978	valid_0's 

In [144]:
print('DOW :',a,'NASDAQ : ',b,'SP500 : ',c)

DOW : 0.5612244897959183 NASDAQ :  0.5591836734693878 SP500 :  0.5673469387755102


In [146]:
print('dow')
get_clf_eval(y_test, lgbm_preds, pred_proba)
print('nasdaq')
get_clf_eval(y_test, lgbm_preds, pred_proba)
print('sp500')
get_clf_eval(y_test, lgbm_preds, pred_proba)

dow
오차 행렬
[[ 14 192]
 [ 23 261]]
정확도: 0.5612, 정밀도: 0.5762, 재현율: 0.9190,    F1: 0.7083, AUC:0.5267
nasdaq
오차 행렬
[[ 14 192]
 [ 23 261]]
정확도: 0.5612, 정밀도: 0.5762, 재현율: 0.9190,    F1: 0.7083, AUC:0.5267
sp500
오차 행렬
[[ 14 192]
 [ 23 261]]
정확도: 0.5612, 정밀도: 0.5762, 재현율: 0.9190,    F1: 0.7083, AUC:0.5267
